connect/connect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path(r'flotilla/', include('connect.flotilla.urls')),
]
=======
    path('usuarios/', include('connect.conductores.urls'))
]
>>>>>>> 9a6cf91602dbaca347068bd668516f06a36a4168

connect/connect/conductores/forms.py
from django import forms
from .models import Conductor, Pasajero, Persona, Hermandad, GENERO_CHOICES, FORMAS_PAGO
from connect.viajes.models import Viaje
from django.forms import TextInput, Select

class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = ['nombre', 'apellidos', 'genero', 'fecnac']
        widgets = {
            'nombre': TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'apellidos': TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'genero': Select(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'fecnac': TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
        }


class ConductorForm(forms.ModelForm):
    class Meta:
        model = Conductor
        fields = ['nombre', 'apellidos', 'genero', 'fecnac', 'licencia', 'entrada', 'salida']


class PasajeroForm(forms.ModelForm):
    class Meta:
        model = Pasajero
        fields = ['nombre', 'apellidos', 'genero', 'fecnac', 'viaje', 'boleto', 'forma_pago']


class HermandadFormSet(forms.BaseInlineFormSet):
    def get_from_kwargs(self, index):
        kwargs = super(HermandadFormSet, self).get_from_kwargs(index)
        kwargs.update({'parent': self.instance})
        return kwargs


class HermandadForm(forms.ModelForm):
    nombre    = forms.CharField(max_length=50, label='Nombre')
    apellidos = forms.CharField(max_length=50, label='Apellidos')
    genero    = forms.ChoiceField(choices=GENERO_CHOICES, label="Genero")
    fecnac    = forms.DateField(label="Fecha de Nacimiento")

    class Meta:
        models = Hermandad
        fields = ['persona_dos', 'nombre', 'apellidos', 'genero']

    def __init__(self, *args, **kwargs):
        self.parent = kwargs.get('parent', None)
        if self.parent is not None:
            del kwargs['parent']

        super(HermandadForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].required = False

            if self.parent is not None:
                self.fields['persona_dos'].queryset = Persona.objects.exclude(id=self.parent.id).all()
                self.fields['persona_dos'].label = 'Seleccionar Persona'

            if self.instance is not None and len(str(self.instance).strip())>0:
                self.fields['nombre'].initial = self.instance.persona_dos.nombre
                self.fields['apellidos'].initial = self.instance.persona_dos.apellidos
                self.fields['genero'].initial = self.instance.persona_dos.genero
                self.fields['fecnac'].initial = self.instance.persona_dos.fecnac
            else:
                pass

connect/templates/usuarios/detalle_persona.html
<html>
    <head>
        <title>Modificar Personas</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <form action="" method="POST">
            {% csrf_token %}
            <!-- <input type="text" name="{{form.nombre.html_name}}" id="id_nombre" class="form-control" value="{{form.nombre.value}}"/>
            <input type="text" name="{{form.apellidos.html_name}}" id="id_apellidos" class="form-control" value="{{form.apellidos.value}}"/>
            <select name="{{form.genero.html_name}}" id="id_genero" class="form-control" value="{{form.genero.value}}">
                <option value="M">Masculino</option>
                <option value="F">Femenino</option>
            </select>
            <input type="date" name="{{form.fecnac.html_name}}" id="id_fecnac" class="form-control" value="{{form.fecnac.value|date:'Y-m-d'}}"/> -->
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a href="/usuarios/personas" class="btn btn-danger">Cancelar</a>
        </form>

        <!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script type="text/javascript">
            $(function() {
                
            });
        </script> -->
    </body>
</html>

connect/templates/usuarios/listado_persona.html
<html>
    <head>
        <title>Personas</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-header">
                        <h3>
                            <span class="ddsicon-settings"></span> Personas  
                            <div class="float-right">
                                <a href="/usuarios/personas/registrar" class="btn btn-link">Registar Persona</a>
                            </div>
                        </h3>
                    </div>
                </div>
            </div>
            <table class="table table-hover table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>No</th>
                        <th>Nombre</th>
                        <th>Genero</th>
                        <th>Fecha de Nacimiento</th>
                        <th>Modificar</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in personas %}
                        <tr>
                            <td>{{p.pk}}</td>
                            <td>{{p.nombre_completo}}</td>
                            <td>{{p.genero}}</td>
                            <td>{{p.fecnac}}</td>
                            <td><a href="{%url 'detalle_persona' p.pk%}">Modificar</a></td>
                            <td><a href="{%url 'eliminar_persona' p.pk%}">Eliminar</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script type="text/javascript">
            $(function() {
                $('#btn-add-persona').click(function() {

                });
            });
        </script> -->
    </body>
</html>

connect/templates/usuarios/persona_agregar.html
<html>
    <head>
        <title>Registrar Persona</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="text" name="{{form.nombre.html_name}}" id="id_nombre" class="form-control" placeholder="Nombre" />
            <input type="text" name="{{form.apellidos.html_name}}" id="id_apellidos" class="form-control" placeholder="Apellidos" />
            <select name="{{form.genero.html_name}}" id="id_genero" class="form-control">
                <option value="M">Masculino</option>
                <option value="F">Femenino</option>
            </select>
            <input type="date" name="{{form.fecnac.html_name}}" id="id_fecnac" class="form-control" />
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a href="/usuarios/personas" class="btn btn-danger">Cancelar</a>
        </form>

        <!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script type="text/javascript">
            $(function() {
                
            });
        </script> -->
    </body>
</html>