connect/connect/flotilla/urls.py
from django.urls import path, include

from .views import (
    current_datetime,
    fetch_hidalgo,
    hola_bootstrap,
    index,
    get_vehiculos,
    add_vehiculo,
)

urlpatterns = [
    path('hoy/', current_datetime, name='hoy'),
    path('muni/', fetch_hidalgo, name='muni'),
    path('holabs/', hola_bootstrap, name='holabs'),


    path('', index, name='index'),
    path('get_vehiculos/', get_vehiculos, name='get_vehiculos'),
    path('add/', add_vehiculo, name='add_vehiculo'),
]

connect/connect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path(r'flotilla/', include('connect.flotilla.urls')),
]
=======
    path('usuarios/', include('connect.conductores.urls'))
]
>>>>>>> 9a6cf91602dbaca347068bd668516f06a36a4168

connect/connect/flotilla/models.py
from django.db import models
from datetime import date

COMBUSTIBLE_CHOICES = [
    ('1', 'DIESEL'),
    ('2', 'GASOLINA')
]

class Vehiculo(models.Model):
    placas = models.CharField(max_length=50, null=False, blank=False)
    vin = models.CharField(max_length=50, null=False, blank=False)
    marca = models.CharField(max_length=50, null=False, blank=False)
    modelo = models.CharField(max_length=50, null=False, blank=False)
    anio = models.DecimalField(max_digits=4, decimal_places=0, null=False, blank=False)
    veirifacion = models.CharField(max_length=50, null=False, blank=False)
    color = models.CharField(max_length=20, null=False, blank=False)
    combustible_tipo = models.CharField(max_length=1, null=False, blank=False, choices=COMBUSTIBLE_CHOICES, default='2')
    combustible_capacidad = models.IntegerField(null=False, blank=False, default=0)
    num_asientos = models.IntegerField(null=False, blank=False)
    num_puertas = models.IntegerField(null=False, blank=False)
    verificacion = models.DateField(default=date.today())

    class Meta:
        verbose_name = 'Vehiculos'
        verbose_name_plural = 'Vehiculos'

    def __str__(self):
        return '{}:{}:{}:{}'.format(self.marca, self.modelo, self.anio, self.placas)

    @property
    def vehiculo(self):
        return '{} {} {}'.format(self.marca, self.modelo, self.anio)

class Camioneta(Vehiculo):
    class Meta:
        verbose_name = 'Camionetas'
        verbose_name_plural = 'Camionetas'

class Autobus(Vehiculo):
    tiene_banio = models.BooleanField(null=False, default=True, blank=False)

    class Meta:
        verbose_name = 'Autobuses'
        verbose_name_plural = 'Autobuses'

    def __str__(self):
        return '{}: {} tiene baño'.format(self.placas, 'si' if self.tiene_banio else 'no')

connect/connect/flotilla/forms.py
from django import forms
from django.forms import DateField

from .models import Vehiculo, Autobus, Camioneta


class VehiculoForm(forms.ModelForm):

    class Meta:
        model = Vehiculo
        fields = []

        labels = {
            'anio': 'Año',
        }

        help_texts = {
            'verificacion': 'Ultima fecha de verificación',
        }

        ANIOS_LIST = range(2000, 2019)
        ANIOS = [(2001, 2001), (2002, 2002)]
        # anio = forms.DateInput(widget=forms.SelectDateWidget(years=ANIOS_LIST))
        widgets = {
            # 'anio': forms.SelectDateWidget(years=ANIOS_LIST)
            # 'anio': forms.ChoiceField(widget=forms.Select, choices=[ANIOS_LIST], required=False)
            # 'anio': forms.Select(None, choices=[ANIOS])
            # 'anio': forms.DateField(widget=forms.SelectDateWidget(years=[ANIOS_LIST]))
        }

    def __init__(self, *args, **kwargs):
        super(VehiculoForm, self).__init__(*args, **kwargs)

        # self.fields['num_asientos'].required = False

        # for field in self.fields:
        #     if field in

connect/connect/flotilla/views.py
from django.http import HttpResponse
from django.shortcuts import render
import datetime
# import requests
from django.template import loader
from django.urls import reverse

from .models import Vehiculo
from .forms import VehiculoForm
from django.http import JsonResponse


def current_datetime(request):
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return HttpResponse(html)

def fetch_hidalgo():
    pass


def hola_bootstrap(request):
    context = {}
    
    return render(request, 'flotilla/hola.html')


def index(request):
    # context = {}
    # return render(request, 'flotilla/index.html')
    personas = Vehiculo.objects.all()

    lista = []
    for index, persona in enumerate(personas):
        lista.append(
            {
                0: str(index + 1),
                1: persona.marca,
                2: persona.modelo,
                3: persona.placas,
                4: persona.color,
                'link': {
                    'url': 'flhnh',
                    'label': 'Detalle'
                },
            }
        )

    lista_data = {
        'lista': lista,
        'columnas': [
            'No.', 'Marca', 'Modelo', 'Placas', 'Color', 'Detalle'
        ]
    }

    context = {
        'lista': lista_data,
    }
    template = loader.get_template('flotilla/index.html')
    return HttpResponse(template.render(context, request))


def get_vehiculos(request):
    vehiculos = Vehiculo.objects.all().values()  # or simply .values() to get all fields
    vehiculos_list = list(vehiculos)  # important: convert the QuerySet to a list object
    return JsonResponse(vehiculos_list, safe=False)


def add_vehiculo(request):
    form = VehiculoForm()
    if request.method == 'POST':
        # form = VehiculoForm(request.POST)
        #cform = Vehiculo(request.POST)
        # form = Vehiculo(marca='asfafs', modelo='sdfdg', placas='djknsjdg')
        form = Vehiculo(marca=request.POST.get('marca',''), modelo=request.POST.get('modelo',''), placas=request.POST.get('placas',''))
        
        form.anio = 2019
        form.num_asientos = 15
        form.num_puertas = 3

        form.save()
        return JsonResponse([True], safe=False)

        '''
        form.marca = 'ksbdgs'
        form.modelo = 'ksbdgs'
        form.placas = 'ksbdgs'
        form.anio = 2019
        if form.is_valid():
            form.save()
            return JsonResponse([True], safe=False)
        '''

connect/templates/flotilla/index.html
{% include "header.html" %}


  <div class="container">

    <h3>
      Vehiculos registrados
      <button type="button" class="btn btn-sm btn-primary pull-right" data-toggle="modal" data-target="#frm-item"><i class="fa fa-plus"></i> Agregar</button>
    </h3>

    <table id="tbl-items" class="table table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Vehiculo</th>
                <th>Placas</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                
            </tr>
        </tbody>
    </table>

  </div>

  <div id="frm-item" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Datos del vehículo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1">Marca</label>
            <input type="text" class="form-control" id="id_marca" name="marca" aria-describedby="emailHelp">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Modelo</label>
            <input type="text" class="form-control" id="id_modelo" name="modelo" aria-describedby="emailHelp">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Placas</label>
            <input type="text" class="form-control" id="id_placas" name="placas" aria-describedby="emailHelp">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" id="btnSave">Guardar</button>
      </div>
    </div>
  </div>
</div>

{% include "footer.html" %}

<script>
$(document).ready(function(){

  $urlApi = 'http://0.0.0.0:8000/flotilla/';

  getAll();

  function getAll(){
    $('#tbl-items tbody').empty();
    $.get($urlApi+'get_vehiculos/', function(data){
      $.each(data, function(i,item){
        tr = $('<tr></tr>');
        tr.append('<td>'+item.marca+' '+item.modelo+'</td>');
        tr.append('<td>'+item.placas+'</td>');

        $('#tbl-items tbody').append(tr);
      });
    },'json');
  }

  $('#btnSave').click(function(){
    data = {marca: $('#id_marca').val(), 
    modelo: $('#id_modelo').val(), 
    placas: $('#id_placas').val(), 
    csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(), 
    anio: 2019}

    $.post($urlApi+'add/', data, function(data){
      getAll();
      $('#frm-item').modal('hide');
    },'json');
  });

});
</script>